tags:
  demo: true
  docs: false

# Demo site
apache:
  image:
    repository: alanaktion/phproject
    tag: apache
    pullPolicy: Always
  containerPorts:
    http: 80
    https: 443
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    fsGroup: 33
  ingress:
    enabled: true
    hostname: demo.phproject.org
  extraVolumes:
    - name: uploads
      emptyDir: {}
    - name: tmp
      emptyDir: {}
    - name: config
      configMap:
        name: phproject-config
  extraVolumeMounts:
    - name: uploads
      mountPath: /var/www/html/uploads
    - name: tmp
      mountPath: /var/www/html/tmp
    - name: config
      mountPath: /var/www/html/config.php
      subPath: config.php
  extraDeploy:
    - |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: phproject-config
        labels: {{- include "common.labels.standard" . | nindent 6 }}
          {{- if .Values.commonLabels }}
          {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 6 }}
          {{- end }}
        {{- if .Values.commonAnnotations }}
        annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 6 }}
        {{- end }}
      data:
        config.php: |-
          <?php
          return [
            'db.host' => 'phproject-mariadb',
            'db.port' => '3306',
            'db.user' => 'phproject',
            'db.pass' => 'demo',
            'db.name' => 'phproject',
            'site.url' => 'https://demo.phproject.org/',
          ];

mariadb:
  auth:
    database: phproject
    username: phproject
    password: demo
    rootPassword: demo
  primary:
    persistence:
      enabled: true
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 10Gi

# Docs site
nginx:
  cloneStaticSiteFromGit:
    enabled: true
    repository: https://github.com/Alanaktion/phproject.git
    branch: gh-pages
    interval: 3600
    # TODO: run incremental jekyll build after clone and sync
    # gitSync:
    #   command:
    #     - /bin/bash
    #     - -ec
    #     - |
    #       [[ -f "/opt/bitnami/scripts/git/entrypoint.sh" ]] && source "/opt/bitnami/scripts/git/entrypoint.sh"
    #       while true; do
    #         cd /app && git pull origin gh-pages
    #         sleep 3600
    #       done
  ingress:
    enabled: true
    hostname: www.phproject.org
    extraHosts:
      - name: phproject.org
        path: /
  # TODO: configure nginx to serve _site build dir
  # serverBlock: |-
  # server {
  #   listen 0.0.0.0:8080;
  #   location / {
  #     return 200 "hello!";
  #   }
  # }
