apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo.fullname" . }}-data
  labels:
    {{- include "demo.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "files/*").AsConfig | nindent 2 }}
